"""add table_id

Revision ID: 12ce532bbee3
Revises: 8ab575a301cc
Create Date: 2025-08-19 13:25:32.890685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12ce532bbee3'
down_revision: Union[str, Sequence[str], None] = '8ab575a301cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mk')
    op.drop_table('j')
    op.add_column('dashboard_items', sa.Column('table_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dashboard_items', 'meta_tabla', ['table_id'], ['id'])
    op.drop_column('dashboard_items', 'table_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard_items', sa.Column('table_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'dashboard_items', type_='foreignkey')
    op.drop_column('dashboard_items', 'table_id')
    op.create_table('j',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('j_pkey'))
    )
    op.create_table('mk',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('mk_pkey'))
    )
    # ### end Alembic commands ###
