"""replace table_id FK with table_name

Revision ID: 8ab575a301cc
Revises: 
Create Date: 2025-08-17 11:47:38.793697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab575a301cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=50), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tabla_1')
    op.drop_table('zzzz')
    op.drop_table('zz')
    op.drop_table('gfjfjdfj')
    op.drop_table('jk')
    op.drop_table('cgg')
    op.drop_table('cg')
    op.drop_table('ventas')
    op.drop_table('register_1')
    op.drop_table('xxx')
    op.drop_table('guu')
    op.drop_table('cc')
    op.drop_table('reg_1')
    op.drop_table('zzz')
    op.drop_table('ventasapple')
    op.add_column('dashboard_items', sa.Column('refresh_interval', sa.Integer(), nullable=True))
    op.add_column('dashboard_items', sa.Column('last_refresh', sa.DateTime(), nullable=True))
    op.alter_column('dashboard_items', 'table_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               nullable=True)
    op.alter_column('dashboard_items', 'item_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_foreign_key(None, 'dashboard_items', 'dashboards', ['dashboard_id'], ['id'])
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.create_unique_constraint(None, 'usuario', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuario', type_='unique')
    op.alter_column('usuario', 'email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
    op.drop_constraint(None, 'dashboard_items', type_='foreignkey')
    op.alter_column('dashboard_items', 'item_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('dashboard_items', 'table_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_column('dashboard_items', 'last_refresh')
    op.drop_column('dashboard_items', 'refresh_interval')
    op.create_table('ventasapple',
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('zzz',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('reg_1',
    sa.Column('FECHA', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('AUTORIDADES', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('cc',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('guu',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guu_pkey'))
    )
    op.create_table('xxx',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('register_1',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('ventas',
    sa.Column('producto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('precio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('cg',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('cgg',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('jk',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('gfjfjdfj',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('gfjfjdfj_pkey'))
    )
    op.create_table('zz',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('zzzz',
    sa.Column('fecha', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('autoridades', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_table('tabla_1',
    sa.Column('FECHA', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Signatura', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('AUTORIDADES', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Número_de_control', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.drop_table('dashboards')
    # ### end Alembic commands ###
